/*
 * Diarization documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DiarizationParam
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T23:25:12.859+03:00")
public class DiarizationParam {
  @SerializedName("audio")
  private Audio audio = null;

  public DiarizationParam(Audio audio) {
    this.audio = audio;
  }

  public DiarizationParam audio(Audio audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Audio for diarization
   * @return audio
  **/
  @ApiModelProperty(required = true, value = "Audio for diarization")
  public Audio getAudio() {
    return audio;
  }

  public void setAudio(Audio audio) {
    this.audio = audio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiarizationParam diarizationParam = (DiarizationParam) o;
    return Objects.equals(this.audio, diarizationParam.audio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiarizationParam {\n");

    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

