/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.158
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AdvancedRecognitionRequestDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-15T12:12:05.337+03:00")
public class AdvancedRecognitionRequestDto {
  /**
   * Recognize with package
   */

  @SerializedName("package_id")
  private String packageId;

  @SerializedName("channels")
  private List<Integer> channels;

  @SerializedName("data")
  private byte[] data;

  public AdvancedRecognitionRequestDto(byte[] data, List<Integer> channels, String packageId) {
    this.packageId = packageId;
    this.channels = channels;
    this.data = data;
  }

  public AdvancedRecognitionRequestDto packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Recognize with package
   * @return packageId
  **/
  @ApiModelProperty(example = "SpontRus-2", value = "Recognize with package")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public AdvancedRecognitionRequestDto channels(List<Integer> channels) {
    this.channels = channels;
    return this;
  }

  public AdvancedRecognitionRequestDto addChannelsItem(Integer channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<Integer>();
    }
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * Specific channels to process
   * @return channels
  **/
  @ApiModelProperty(value = "Specific channels to process")
  public List<Integer> getChannels() {
    return channels;
  }

  public void setChannels(List<Integer> channels) {
    this.channels = channels;
  }

  public AdvancedRecognitionRequestDto data(byte[] data) {
    this.data = data;
    return this;
  }

   /**
   * Binary audio file (Wav format) data as Base64 string
   * @return data
  **/
  @ApiModelProperty(example = "\"TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCAuLi4=\"", required = true, value = "Binary audio file (Wav format) data as Base64 string")
  public byte[] getData() {
    return data;
  }

  public void setData(byte[] data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvancedRecognitionRequestDto advancedRecognitionRequestDto = (AdvancedRecognitionRequestDto) o;
    return Objects.equals(this.packageId, advancedRecognitionRequestDto.packageId) &&
        Objects.equals(this.channels, advancedRecognitionRequestDto.channels) &&
        Objects.equals(this.data, advancedRecognitionRequestDto.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageId, channels, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdvancedRecognitionRequestDto {\n");

    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

