/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.158
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ASRAdvancedResultDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-15T12:12:05.337+03:00")
public class ASRAdvancedResultDto {
  @SerializedName("channel_id")
  private Integer channelId = null;

  @SerializedName("result")
  private List<WordDto> result = new ArrayList<WordDto>();

  public ASRAdvancedResultDto channelId(Integer channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * Channel id
   * @return channelId
  **/
  @ApiModelProperty(example = "0", required = true, value = "Channel id")
  public Integer getChannelId() {
    return channelId;
  }

  public void setChannelId(Integer channelId) {
    this.channelId = channelId;
  }

  public ASRAdvancedResultDto result(List<WordDto> result) {
    this.result = result;
    return this;
  }

  public ASRAdvancedResultDto addResultItem(WordDto resultItem) {
    this.result.add(resultItem);
    return this;
  }

   /**
   * Recognition result
   * @return result
  **/
  @ApiModelProperty(required = true, value = "Recognition result")
  public List<WordDto> getResult() {
    return result;
  }

  public void setResult(List<WordDto> result) {
    this.result = result;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ASRAdvancedResultDto asRAdvancedResultDto = (ASRAdvancedResultDto) o;
    return Objects.equals(this.channelId, asRAdvancedResultDto.channelId) &&
        Objects.equals(this.result, asRAdvancedResultDto.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ASRAdvancedResultDto {\n");

    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

