/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AudioFileDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class AudioFileDto {
  @SerializedName("data")
  private byte[] data = new byte[]{};

  @SerializedName("mime")
  private String mime = null;

  public AudioFileDto(byte[] data, String mime) {
    this.data = data;
    this.mime = mime;
  }

  public AudioFileDto data(byte[] data) {
    this.data = data;
    return this;
  }

   /**
   * Binary audio file (Wav format) data as Base64 string
   * @return data
  **/
  @ApiModelProperty(example = "\"TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCBvbmx5IGJ5IGhpcyByZWFzb24sIGJ1dCAuLi4=\"", required = true, value = "Binary audio file (Wav format) data as Base64 string")
  public byte[] getData() {
    return data;
  }

  public void setData(byte[] data) {
    this.data = data;
  }

  public AudioFileDto mime(String mime) {
    this.mime = mime;
    return this;
  }

   /**
   * Audio file mime type
   * @return mime
  **/
  @ApiModelProperty(example = "audio/x-wav", required = true, value = "Audio file mime type")
  public String getMime() {
    return mime;
  }

  public void setMime(String mime) {
    this.mime = mime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AudioFileDto audioFileDto = (AudioFileDto) o;
    return Objects.equals(this.data, audioFileDto.data) &&
        Objects.equals(this.mime, audioFileDto.mime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, mime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AudioFileDto {\n");

    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

