/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PackageDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class PackageDto {
  @SerializedName("package_id")
  private String packageId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("sample_rate")
  private Integer sampleRate = null;

  @SerializedName("loaded")
  private Boolean loaded = null;

  public PackageDto(String packageId, String name, String language, Integer sampleRate, Boolean loaded) {
    this.packageId = packageId;
    this.name = name;
    this.language = language;
    this.sampleRate = sampleRate;
    this.loaded = loaded;
  }

  public PackageDto packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Package ID
   * @return packageId
  **/
  @ApiModelProperty(example = "CommonRespeakingRus-1", required = true, value = "Package ID")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public PackageDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Package name
   * @return name
  **/
  @ApiModelProperty(example = "CommonRespeakingRus-1", required = true, value = "Package name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageDto language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Package language
   * @return language
  **/
  @ApiModelProperty(example = "ru", required = true, value = "Package language")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public PackageDto sampleRate(Integer sampleRate) {
    this.sampleRate = sampleRate;
    return this;
  }

   /**
   * Required sample rate of data
   * @return sampleRate
  **/
  @ApiModelProperty(example = "16000", required = true, value = "Required sample rate of data")
  public Integer getSampleRate() {
    return sampleRate;
  }

  public void setSampleRate(Integer sampleRate) {
    this.sampleRate = sampleRate;
  }

  public PackageDto loaded(Boolean loaded) {
    this.loaded = loaded;
    return this;
  }

   /**
   * Is package loaded to the cache
   * @return loaded
  **/
  @ApiModelProperty(example = "false", required = true, value = "Is package loaded to the cache")
  public Boolean isLoaded() {
    return loaded;
  }

  public void setLoaded(Boolean loaded) {
    this.loaded = loaded;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageDto packageDto = (PackageDto) o;
    return Objects.equals(this.packageId, packageDto.packageId) &&
        Objects.equals(this.name, packageDto.name) &&
        Objects.equals(this.language, packageDto.language) &&
        Objects.equals(this.sampleRate, packageDto.sampleRate) &&
        Objects.equals(this.loaded, packageDto.loaded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageId, name, language, sampleRate, loaded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageDto {\n");

    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    sampleRate: ").append(toIndentedString(sampleRate)).append("\n");
    sb.append("    loaded: ").append(toIndentedString(loaded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

