/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RecognitionRequestDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class RecognitionRequestDto {
  @SerializedName("audio")
  private AudioFileDto audio = null;

  public RecognitionRequestDto(AudioFileDto audio, String packageId) {
    this.audio = audio;
    this.packageId = packageId;
  }

  /**
   * Recognize with package
   */

  @SerializedName("package_id")
  private String packageId = null;

  public RecognitionRequestDto audio(AudioFileDto audio) {
    this.audio = audio;
    return this;
  }

   /**
   * Audio file data and description
   * @return audio
  **/
  @ApiModelProperty(required = true, value = "Audio file data and description")
  public AudioFileDto getAudio() {
    return audio;
  }

  public void setAudio(AudioFileDto audio) {
    this.audio = audio;
  }

  public RecognitionRequestDto packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Recognize with package
   * @return packageId
  **/
  @ApiModelProperty(example = "SpontRus-2", value = "Recognize with package")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognitionRequestDto recognitionRequestDto = (RecognitionRequestDto) o;
    return Objects.equals(this.audio, recognitionRequestDto.audio) &&
        Objects.equals(this.packageId, recognitionRequestDto.packageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audio, packageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognitionRequestDto {\n");

    sb.append("    audio: ").append(toIndentedString(audio)).append("\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

