/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SessionlessRecognitionRequestDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class SessionlessRecognitionRequestDto {
  @SerializedName("user_info")
  private StartSessionRequest userInfo = null;

  @SerializedName("recognition_request")
  private RecognitionRequestDto recognitionRequest = null;

  public SessionlessRecognitionRequestDto(StartSessionRequest userInfo, RecognitionRequestDto recognitionRequest) {
    this.userInfo = userInfo;
    this.recognitionRequest = recognitionRequest;
  }

  public SessionlessRecognitionRequestDto userInfo(StartSessionRequest userInfo) {
    this.userInfo = userInfo;
    return this;
  }

   /**
   * User credentials
   * @return userInfo
  **/
  @ApiModelProperty(required = true, value = "User credentials")
  public StartSessionRequest getUserInfo() {
    return userInfo;
  }

  public void setUserInfo(StartSessionRequest userInfo) {
    this.userInfo = userInfo;
  }

  public SessionlessRecognitionRequestDto recognitionRequest(RecognitionRequestDto recognitionRequest) {
    this.recognitionRequest = recognitionRequest;
    return this;
  }

   /**
   * User credentials
   * @return recognitionRequest
  **/
  @ApiModelProperty(required = true, value = "User credentials")
  public RecognitionRequestDto getRecognitionRequest() {
    return recognitionRequest;
  }

  public void setRecognitionRequest(RecognitionRequestDto recognitionRequest) {
    this.recognitionRequest = recognitionRequest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionlessRecognitionRequestDto sessionlessRecognitionRequestDto = (SessionlessRecognitionRequestDto) o;
    return Objects.equals(this.userInfo, sessionlessRecognitionRequestDto.userInfo) &&
        Objects.equals(this.recognitionRequest, sessionlessRecognitionRequestDto.recognitionRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userInfo, recognitionRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionlessRecognitionRequestDto {\n");

    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("    recognitionRequest: ").append(toIndentedString(recognitionRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

