/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StreamRequestDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class StreamRequestDto {
  /**
   * Recognize with package
   */

  @SerializedName("package_id")
  private String packageId = null;

  @SerializedName("mime")
  private String mime = null;

  public StreamRequestDto(String packageId, String mime) {
    this.packageId = packageId;
    this.mime = mime;
  }

  public StreamRequestDto packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Recognize with package
   * @return packageId
  **/
  @ApiModelProperty(example = "CommonRespeakingRus-1", value = "Recognize with package")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public StreamRequestDto mime(String mime) {
    this.mime = mime;
    return this;
  }

   /**
   * Audio file mime type
   * @return mime
  **/
  @ApiModelProperty(example = "audio/L16", required = true, value = "Audio file mime type")
  public String getMime() {
    return mime;
  }

  public void setMime(String mime) {
    this.mime = mime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamRequestDto streamRequestDto = (StreamRequestDto) o;
    return Objects.equals(this.packageId, streamRequestDto.packageId) &&
        Objects.equals(this.mime, streamRequestDto.mime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageId, mime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamRequestDto {\n");

    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    mime: ").append(toIndentedString(mime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

