/*
 * ASR documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.58
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.speechpro.cloud.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * WordDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-12T21:20:53.133+03:00")
public class WordDto {
  @SerializedName("word")
  private String word = null;

  @SerializedName("score")
  private String score = null;

  @SerializedName("begin")
  private String begin = null;

  @SerializedName("length")
  private String length = null;

  public WordDto word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Recognized word
   * @return word
  **/
  @ApiModelProperty(example = "apple", required = true, value = "Recognized word")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }

  public WordDto score(String score) {
    this.score = score;
    return this;
  }

   /**
   * Recognition confidence (0 - 100.00)
   * @return score
  **/
  @ApiModelProperty(example = "75.45", required = true, value = "Recognition confidence (0 - 100.00)")
  public String getScore() {
    return score;
  }

  public void setScore(String score) {
    this.score = score;
  }

  public WordDto begin(String begin) {
    this.begin = begin;
    return this;
  }

   /**
   * Time stamp on which this word was found
   * @return begin
  **/
  @ApiModelProperty(example = "4.36", value = "Time stamp on which this word was found")
  public String getBegin() {
    return begin;
  }

  public void setBegin(String begin) {
    this.begin = begin;
  }

  public WordDto length(String length) {
    this.length = length;
    return this;
  }

   /**
   * Word duration
   * @return length
  **/
  @ApiModelProperty(example = "0.32", value = "Word duration")
  public String getLength() {
    return length;
  }

  public void setLength(String length) {
    this.length = length;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WordDto wordDto = (WordDto) o;
    return Objects.equals(this.word, wordDto.word) &&
        Objects.equals(this.score, wordDto.score) &&
        Objects.equals(this.begin, wordDto.begin) &&
        Objects.equals(this.length, wordDto.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(word, score, begin, length);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WordDto {\n");

    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    begin: ").append(toIndentedString(begin)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

